### ISSUE TITLE
Feat: Add a new order state indicating transfer is sucessful

### ISSUE THREAD

**Issue by Halimao** [fox-one/4swap-sdk-go#15]
### Feat: Add a new order state indicating transfer is sucessful

After make a transfer request to mtg-transaction, the order [state](https://github.com/fox-one/4swap-sdk-go/blob/master/order.go#L11-L13) (response from [ReadOrder](https://github.com/fox-one/4swap-sdk-go/blob/master/order.go#L96)) only has three state
```Go
const (
	OrderStateTrading  = "Trading"
	OrderStateRejected = "Rejected"
	OrderStateDone     = "Done"
)
```
thereby, we couldn't know is the transfer of this order successful then?
Maybe we can add a new state just like ``` OrderStateTransferDone  = "TransferDone" ```, and update order state to OrderStateTransferDone after 4swap transfer to MixinNetwork.

**Comment by yiplee** [comment]
The transfer done state should be updated by pulling network snapshots to ensue the transfer is done on your side.

The transfer done on 4swap side does not mean the balance of your wallet increased.
