### ISSUE TITLE
pre-order wrong price

### ISSUE THREAD

**Issue by who3m1** [fox-one/4swap-sdk-go#17]
I wrote a function using preorder to query BOX price.
![Pic1](https://user-images.githubusercontent.com/36271125/132486626-fca21a67-ed5b-46a6-8410-54d44362749d.png)
At that moment, what I got in return is 5.3734 USDT/BOX.
![Pic2](https://user-images.githubusercontent.com/36271125/132487036-d3bedec3-c784-4aa2-b309-df23538747e3.png)
But when I query the API with POST.
![Pic3](https://user-images.githubusercontent.com/36271125/132487269-68302418-ac83-4bf3-8097-09fe552870f6.png)
It shows the price is 6.0031 USDT/BOX
![pic4](https://user-images.githubusercontent.com/36271125/132487369-eac7770a-37e3-4a7b-bc96-708e8333bb25.png)
I'm not sure if this is a bug.

**Comment by cw35** [comment]
I think it is not a bug. Your two queries come with different routes, this maybe the reason of different price.

**Comment by who3m1** [comment]
You are right, I thought it would find the best route by default. But it shows it doesn't. Thank you for replying.
![image](https://user-images.githubusercontent.com/36271125/132497443-ea4a2e0e-4fa1-4c72-93d0-e90f6784bf04.png)
