### ISSUE TITLE
[Question] 是否错误标注 PreOrderReq.MinAmount 字段 deprecated

### ISSUE THREAD

**Issue by Kuri-su** [fox-one/4swap-sdk-go#8]
从新增的字段上来看, 似乎deprecated 的是 Amount 字段,而非 MinAmount 字段. 从 Swap 的角度, 也不太可能取消PreOrder的 滑点吧?

https://github.com/fox-one/4swap-sdk-go/blob/35cd4091165e41036f85d4654a2d2c421f1b8497/order.go#L34-L46

**Comment by yiplee** [comment]
pr 我合了，仔细看了下，这个 MinAmount  的确是被 deprecated 了，PreOrder 是预下单，是为了获取预估买入量，并没有真正下单。

**Comment by Kuri-su** [comment]
ok ,那我再提一个 PR 去把 MinAmount 给 deprecated, 忘了是 PreOrderReq 里面
